# -*- coding: utf-8 -*-
"""Day 1 Python project Project (1st)  :

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPsyZYPBscghNlK7ODbmDOg9YW7XzkNh
"""

print("welcome to the Band Name Generator")
city = input("What is the name of the city you live in?")
pet = input ("what is the name of your pet?")
print("Your band name could be " + city + " " + pet)