# -*- coding: utf-8 -*-
"""Day 2 Python project Project (2nd)  :

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPsyZYPBscghNlK7ODbmDOg9YW7XzkNh
"""

print("Welcome to the Tip Calculator")

bill = float(input("How much was the total bill? "))
tip_percentage = int(input("How much tip would you like to give? 10, 12, 15 or 20? "))
group = int(input("How many ways is this bill being split? "))

# Calculate the tip amount
tip_amount = bill * (tip_percentage / 100)

# Calculate the total bill
total_bill = bill + tip_amount

# Calculate the bill per person
bill_per_person = round(total_bill / group, 2)

print("Each person owes:", bill_per_person)
print("Thank you for dining with us. We hope you enjoyed your time.")